C_OBJ += $(MBED_LIB_DIR)/EthernetInterface/lwip-eth/arch/TARGET_RZ_A1H/rza1_emac.o \
      	 $(MBED_LIB_DIR)/EthernetInterface/lwip-sys/arch/checksum.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip-sys/arch/memcpy.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip-sys/arch/sys_arch.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/netif/etharp.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/netif/ethernetif.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/netif/slipif.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/netif/ppp/auth.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/netif/ppp/chap.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/netif/ppp/chpms.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/netif/ppp/fsm.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/netif/ppp/ipcp.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/netif/ppp/lcp.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/netif/ppp/magic.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/netif/ppp/md5.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/netif/ppp/pap.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/netif/ppp/ppp.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/netif/ppp/ppp_oe.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/netif/ppp/randm.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/netif/ppp/vj.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/api/api_lib.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/api/api_msg.o \
 	 $(MBED_LIB_DIR)/EthernetInterface/lwip/api/err.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/api/netbuf.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/api/netdb.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/api/netifapi.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/api/sockets.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/api/tcpip.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/def.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/dhcp.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/dns.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/init.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/mem.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/memp.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/netif.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/pbuf.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/raw.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/stats.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/tcp.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/tcp_in.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/tcp_out.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/timers.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/udp.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/ipv4/autoip.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/ipv4/icmp.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/ipv4/igmp.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/ipv4/inet.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/ipv4/inet_chksum.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/ipv4/ip.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/ipv4/ip_addr.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/ipv4/ip_frag.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/snmp/asn1_dec.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/snmp/asn1_enc.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/snmp/mib2.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/snmp/mib_structs.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/snmp/msg_in.o \
	 $(MBED_LIB_DIR)/EthernetInterface/lwip/core/snmp/msg_out.o

CXX_OBJ += $(MBED_LIB_DIR)/EthernetInterface/EthernetInterface.o \
	   $(MBED_LIB_DIR)/EthernetInterface/Socket/Endpoint.o \
	   $(MBED_LIB_DIR)/EthernetInterface/Socket/Socket.o \
	   $(MBED_LIB_DIR)/EthernetInterface/Socket/TCPSocketConnection.o \
	   $(MBED_LIB_DIR)/EthernetInterface/Socket/TCPSocketServer.o \
	   $(MBED_LIB_DIR)/EthernetInterface/Socket/UDPSocket.o

INCLUDE_PATHS += -I$(MBED_LIB_DIR)/EthernetInterface \
		 -I$(MBED_LIB_DIR)/EthernetInterface/Socket \
  		 -I$(MBED_LIB_DIR)/EthernetInterface/lwip \
 		 -I$(MBED_LIB_DIR)/EthernetInterface/lwip/include \
 		 -I$(MBED_LIB_DIR)/EthernetInterface/lwip/include/ipv4 \
		 -I$(MBED_LIB_DIR)/EthernetInterface/lwip/core \
		 -I$(MBED_LIB_DIR)/EthernetInterface/lwip/core/ipv4 \
		 -I$(MBED_LIB_DIR)/EthernetInterface/lwip/core/snmp \
		 -I$(MBED_LIB_DIR)/EthernetInterface/lwip/api \
		 -I$(MBED_LIB_DIR)/EthernetInterface/lwip/netif \
		 -I$(MBED_LIB_DIR)/EthernetInterface/lwip/netif/ppp \
 		 -I$(MBED_LIB_DIR)/EthernetInterface/lwip-sys \
		 -I$(MBED_LIB_DIR)/EthernetInterface/lwip-eth/arch/TARGET_RZ_A1H \
		 -I$(MBED_LIB_DIR)/EthernetInterface/cmsis-rtos \
 		 -I$(SRCDIR) \
 		 -I$(SRCDIR)/include \
		 -I$(SRCDIR)/target/gr_peach_gcc \
 		 -I$(SRCDIR)/arch \
 		 -I$(SRCDIR)/arch/arm_gcc/common \
  		 -I.

CDEFS += -DTARGET_RZ_A1H
