CXX_OBJ += $(MBED_LIB_DIR)/mbed-rpc/Arguments.o \
	   $(MBED_LIB_DIR)/mbed-rpc/RPCFunction.o \
	   $(MBED_LIB_DIR)/mbed-rpc/parse_pins.o \
	   $(MBED_LIB_DIR)/mbed-rpc/rpc.o

INCLUDE_PATHS += -I$(MBED_LIB_DIR)/mbed-rpc
